### ISSUE TITLE
Can't group must-link data into one cluster

### ISSUE THREAD

**Issue by SuYanqi** [bhrzslm/copkmeans#10]
I use this algorithm in my dataset, but I find data which is in the must-link set are in the two cluster. Hope your reply, thanks

**Comment by Behrouz-Babaki** [comment]
I'd be happy to check this. Can you send me the data for which you have observed this behavior, and the command line that you have used? (You can find my contact information [here](https://behrouzbabaki.bitbucket.io/))

**Comment by SuYanqi** [comment]
Sorry to bother you, I have checked my dataset and found it was my fault. The algorithm is perfect and help me a lot. Thanks so much.
