### ISSUE TITLE
Predict method

### ISSUE THREAD

**Issue by lachhebo** [bhrzslm/copkmeans#14]
Hi, 

Is it possible to implement a predict method like in the sklearn implementation of KMeans. 

If you think it is resonnable, i could try to implement it my self.

**Comment by Behrouz-Babaki** [comment]
Sorry for not noticing this issue earlier. In the spirit of keeping the code as close as possible to the pseudo-code, I have tried to avoid adding such functionalities. If a user absolutely needs methods similar to those offered by *sklearn*, I think they can easily wrap a function around the existing ones.
