### ISSUE TITLE
Algorithm fails without conflict constraint

### ISSUE THREAD

**Issue by neozhangthe1** [bhrzslm/copkmeans#9]
consider the following case

if we want to cluster x1, x2, x3 into two clusters
with cannot links (x1, x3) and (x2, x3)

we first assign x1 to cluster1, and x2 to cluster2
the algorithm fails because there is no cluster for x3 to be assigned

**Comment by Behrouz-Babaki** [comment]
@neozhangthe1 COP-Kmeans is a greedy algorithm and can not anticipate (or backtrack from) such mistakes. 

*(I have developed another algorithm that recovers from such cases. I will make the implementation publicly available once the paper is published.)*
